site_name: Wojtek Salski Creative Works
site_author: Marcin Salski
site_description: >-
  Portfolio of my creative projects

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

theme:
  name: material

nav:
- Powitanie: index.md
- Projekty analityczne:
  - "Irysy-artykuł": Irysy_a/index.md
  - "Irysy-prezentacja": Irysy_p/index.md
  - "Index BMI": BMI/index.md
  - "Titanic": Titanic/index.md
- Aplikacje:
  - "Audio notatki": Audionotatki/index.md 
  - "Kolorowanki": Kolorowanki/index.md
  - "Znajomi": Znajomi/index.md

  

