site_name: Wojtek Salski Creative Works
site_author: Marcin Salski
site_description: >-
<<<<<<< HEAD
  Portfolio moich projektów informatycznych wykonanych z wykorzystaniem AI i Pythona.
=======
  Portfolio of my creative projects
>>>>>>> 769bc7b9723cb4cb5b315f2cd92e5900e9200ab1

repo_name: MarcinSalski/ws_portfolio
repo_url: https://github.com/MarcinSalski/ws_portfolio

theme:
  name: material

nav:
- Powitanie: index.md
- Projekty analityczne:
  - "Irysy-artykuł": Irysy_a/index.md
  - "Irysy-prezentacja": Irysy_p/index.md
  - "Index BMI": BMI/index.md
  - "Titanic": Titanic/index.md
- Aplikacje:
  - "Audio notatki": Audionotatki/index.md 
  - "Kolorowanki": Kolorowanki/index.md
  - "Znajomi": Znajomi/index.md

  

